# https://www.youtube.com/watch?v=eB0nUzAI7M8
name: Laravel Continuous Integration

# Available events: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [ master ]

jobs:
  npm_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run dev
